//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UO_Atlas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UO_Atlas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] FireBirdFiles {
            get {
                object obj = ResourceManager.GetObject("FireBirdFiles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InformationIcon {
            get {
                object obj = ResourceManager.GetObject("InformationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LabelCategoryIcons {
            get {
                object obj = ResourceManager.GetObject("LabelCategoryIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARCHERSGUILD
        ///ARMAMENTSGUILD
        ///ARMOURERSGUILD
        ///ARMS
        ///ASSASINSGUILD
        ///BAKER
        ///BANK
        ///BARBERSHOP
        ///BARD
        ///BARDICGUILD
        ///BEEKEEPER
        ///BLACKSMITH
        ///BLACKSMITHSGUILD
        ///BODYOFWATER
        ///BOWYER
        ///BRASS
        ///BRIDGE
        ///BUTCHER
        ///CARPENTER
        ///CASTLE
        ///CAVALRYGUILD
        ///COOKSGUILD
        ///CUSTOMS
        ///DOCKS
        ///DUNGEON
        ///EXIT
        ///FIGHTERSGUILD
        ///FISHERMANSGUILD
        ///FLETCHER
        ///GATE
        ///GEM
        ///GRAVEYARD
        ///GUILD
        ///HAND
        ///HEALER
        ///HEALERSGUILD
        ///ILLUSIONISTSGUILD
        ///INN
        ///POINTOFINTEREST
        ///ISLAND
        ///JEWELER
        ///KEEP
        ///LANDMARK
        ///LARGEHOUSE
        ///LGBOATE
        ///LGBOATN
        ///LGBOATS
        ///LGBOATW
        ///LIBRARY
        ///LOGCABIN        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MapLabelCategories {
            get {
                return ResourceManager.GetString("MapLabelCategories", resourceCulture);
            }
        }
        
        internal static byte[] Shell32 {
            get {
                object obj = ResourceManager.GetObject("Shell32", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
